### ISSUE TITLE
Login Front End

### ISSUE THREAD

**Issue by Wieworki** [Wieworki/Web-project-with-PHP#20]
Improve the login interface. Right now it is lacking a return button, and the menu bar.

The CSS should be improved too, so it makes the page more appealing. We can try to use Bootstrap

**Comment by PelusoDv** [comment]
I added a return button to the main page and improved the style of the CSS implementig Bootstrap to make all more responsive to diferent resolutions. 
Next step will be add a menu bar to make it more navegable.

**Comment by PelusoDv** [comment]
"Finished" the navigation bar and the login page, we need to test the functionality and maybe make improvements to the designe and/or the backgroun imagen and bussiness logo.
