### ISSUE TITLE
Fix the user management table display

### ISSUE THREAD

**Issue by Wieworki** [Wieworki/Web-project-with-PHP#42]
When the page width is small, the table columns doesn't fit the table

![Screenshot 2022-06-03 at 15-39-35 Administración de usuarios](https://user-images.githubusercontent.com/45775681/171930379-9e169576-cdcf-4d8e-b44c-b21818959af1.png)

This needs to be fixed, in case the user needs to access this page in a mobile device. We can try with the "@media" property, that may let us adapt the size of the columns and the table according the width and height of the device.

**Comment by PelusoDv** [comment]
fixed the problem adding a horizontal scrollbar so it shows when the width resolution is lower than HD. I think it would be more helpfull than re-sizing the table columns or making them change it's positions in lower resolutions. Just let me know what you think about
