### ISSUE TITLE
Revamp the user catalog table

### ISSUE THREAD

**Issue by Wieworki** [Wieworki/Web-project-with-PHP#51]
Now that there catalog table is functional, it needs to look good. This is the main page that the costumers will se, so we need to make it appealing. Feel free to change anything from the table structure, but keep the number of rows to 5, or the data won´t be loaded correctly from the DB.

**Comment by PelusoDv** [comment]
Just finished the new good looking Main page hehe, let me know if ther is something you think we can change

**Comment by Wieworki** [comment]
The new search function needs some work. It should'n show the unordered list symbol for each of the options. It could be more visually appealing too.

**Comment by PelusoDv** [comment]
finished with the styling of the new search function so it machs better with the style of the main page
